service: express-lambda

provider:
  name: aws
  region: ap-south-1
  runtime: nodejs20.x
  memorySize: 512
  timeout: 29
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    SUPABASE_PROJECT_URL: ${env:SUPABASE_PROJECT_URL}
    SUPABASE_SUPER_ADMIN: ${env:SUPABASE_SUPER_ADMIN}
    RAZORPAY_API_KEY: ${env:RAZORPAY_API_KEY}
    RAZORPAY_SECRET: ${env:RAZORPAY_SECRET}
    RAZORPAY_PLAN_ID_199: ${env:RAZORPAY_PLAN_ID_199}
    CRYPTO_SECRET: ${env:CRYPTO_SECRET}
    RAZORPAY_WEBHOOK_SECRET: ${env:RAZORPAY_WEBHOOK_SECRET}
  deploymentBucket:
    maxPreviousDeploymentArtifacts: 3
    
functions:
  app:
    handler: handler.handler
    events:
      - httpApi: '*'

package:
  patterns:
    - '!.env'
    - '!.env.*'     
    - '!README.md'
    - '!.gitignore'
