name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            backend
          sparse-checkout-cone-mode: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Install Serverless
        run: npm install -g serverless

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::840869896762:role/githubOICD
          aws-region: ap-south-1

      - name: Deploy
        run: sls deploy
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SUPABASE_PROJECT_URL: ${{ secrets.SUPABASE_PROJECT_URL }}
          SUPABASE_SUPER_ADMIN: ${{ secrets.SUPABASE_SUPER_ADMIN }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          RAZORPAY_API_KEY: ${{ secrets.RAZORPAY_API_KEY }}
          RAZORPAY_SECRET: ${{ secrets.RAZORPAY_SECRET }}
          RAZORPAY_PLAN_ID_199: ${{ secrets.RAZORPAY_PLAN_ID_199 }}
          CRYPTO_SECRET: ${{ secrets.CRYPTO_SECRET }}
          RAZORPAY_WEBHOOK_SECRET: ${{ secrets.RAZORPAY_WEBHOOK_SECRET }}
          UPSTASH_REDIS_REST_URL: ${{secrets:UPSTASH_REDIS_REST_URL}}
          UPSTASH_REDIS_REST_TOKEN: ${{secrets:UPSTASH_REDIS_REST_TOKEN}}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

